version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    ports:
      - "5050:5050"
    links:
      - mongo
